language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # udagram-api-feed
  - echo "- docker build -t udagram-api-feed"
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed danieljanderson/udagram-api-feed:latest
  - docker tag udagram-api-feed danieljanderson/udagram-api-feed:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danieljanderson/udagram-api-feed:v1
  #udagram-api-user
  - echo "- docker build -t udagram-api-user"
  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user danieljanderson/udagram-api-user:latest
  - docker tag udagram-api-user danieljanderson/udagram-api-user:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danieljanderson/udagram-api-user:v1
  #udagram-frontend
  - echo "- docker build -t udagram-frontend"
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend danieljanderson/udagram-frontend:latest
  - docker tag udagram-frontend danieljanderson/udagram-frontend:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danieljanderson/udagram-frontend:v1
  #udagram-reverseproxy
  - echo "- docker build -t udagram-reverseproxy"
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy danieljanderson/udagram-reverseproxy:latest
  - docker tag udagram-reverseproxy danieljanderson/udagram-reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danieljanderson/udagram-reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node
